# Generated by Django 4.1.2 on 2022-12-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='short_description',
            field=models.TextField(null=True),
        ),
    ]
