# Generated by Django 4.1.2 on 2022-12-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_builder', '0002_rename_school_profile_previous_work_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='intro',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
