# Generated by Django 4.1.2 on 2022-12-18 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_builder', '0007_alter_profile_postauthor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='postAuthor',
        ),
    ]
